version: "3.9"
services:
  database:
    image: "datascientest/mysql-k8s:1.0.0"
    container_name: "mysql_db"
    ports:
      - "3310:3306"
    networks:
      - network-eval-K8S
  api:
    image: "k8s-evaluation-api:0.0.1"
    container_name: "api-evaluation"
    ports:
      - "9200:8000"
    env_file:
      - .env
    networks:
      - network-eval-K8S
networks:
  network-eval-K8S: